PREFIX eco: <https://ggen.dev/ecosystem#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
ASK {
FILTER NOT EXISTS { eco:ggen-ecosystem eco:doesNotOwn ?x . FILTER NOT EXISTS { ?x skos:prefLabel ?label . } }
}
