ASK {
  FILTER NOT EXISTS {
    ?c <http://www.w3.org/2004/02/skos/core#inScheme> <https://ggen.dev/ecosystem#ExclusionScheme> .
    FILTER NOT EXISTS { ?c a <http://www.w3.org/2004/02/skos/core#Concept> . }
  }
}
