PREFIX eco: <https://ggen.dev/ecosystem#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  eco:repo-candidate-mfact-command-center dcterms:identifier "seanchatmangpt/mfact-command-center" ;
      eco:sourceUrl "https://github.com/seanchatmangpt/mfact-command-center" .
}
