PREFIX eco: <https://ggen.dev/ecosystem#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  eco:repo-candidate-weaver dcterms:identifier "seanchatmangpt/weaver" ;
      eco:sourceUrl "https://github.com/seanchatmangpt/weaver" .
}
