PREFIX eco: <https://ggen.dev/ecosystem#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  eco:repo-candidate-aries dcterms:identifier "seanchatmangpt/aries" ;
      eco:sourceUrl "https://github.com/seanchatmangpt/aries" .
}
