PREFIX eco: <https://ggen.dev/ecosystem#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  eco:repo-candidate-fdegym dcterms:identifier "seanchatmangpt/fdegym" ;
      eco:sourceUrl "https://github.com/seanchatmangpt/fdegym" .
}
