PREFIX eco: <https://ggen.dev/ecosystem#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  eco:repo-candidate-lifegym dcterms:identifier "seanchatmangpt/lifegym" ;
      eco:sourceUrl "https://github.com/seanchatmangpt/lifegym" .
}
