PREFIX eco: <https://ggen.dev/ecosystem#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  eco:repo-candidate-ww3gym dcterms:identifier "seanchatmangpt/ww3gym" ;
      eco:sourceUrl "https://github.com/seanchatmangpt/ww3gym" .
}
