PREFIX eco: <https://ggen.dev/ecosystem#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK {
  eco:ProfileShape sh:property [ sh:path eco:selectionPolicy ; sh:maxCount 1 ] .
}
