PREFIX eco: <https://ggen.dev/ecosystem#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK { eco:repo-candidate-release-demos dcterms:identifier "seanchatmangpt/release-demos" ; eco:sourceUrl "https://github.com/seanchatmangpt/release-demos" . }
