PREFIX eco: <https://ggen.dev/ecosystem#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>
ASK { eco:repo-candidate-qlever_poc eco:sourceUrl "https://github.com/seanchatmangpt/qlever_poc" . }
