PREFIX cmd: <https://chatmangpt.com/ontology/cmd#>
PREFIX dcterms: <http://purl.org/dc/terms/>
ASK { <https://ggen.dev/ecosystem/option/prebuilt-ggen> cmd:belongsToDimension <https://ggen.dev/ecosystem/dimension/execution> . }
