PREFIX gha: <http://seanchatmangpt.github.io/packs/github-actions#>
PREFIX ex: <https://ggen.io/ecosystem/github-sync#>
ASK {
  ex:containerCheckout gha:inJob ex:containerBuild . ex:containerLogin gha:inJob ex:containerBuild . ex:containerBuildPush gha:inJob ex:containerBuild .
}
